### PR TITLE
Revert "Merge pull request #41 from Infinite-Worlds-FSA/scoreDisplay"

### PR DESCRIPTION
**Pull request by tstrat**
This reverts commit d64e5bb492b1280d5b250e61608b6b67e96ef019, reversing changes made to 135f83dc84a1af4b33627c8b6676789dc5af724d.

### CODE REVIEW

**Review by kjgumbs — APPROVED** [review]
lgtm

**Review by kjgumbs — APPROVED** [review]
lgtm

**Review by kjgumbs — APPROVED** [review]

**Review by kjgumbs — APPROVED** [review]
lgtm

**Comment by kjgumbs** [comment]
lgtm

**Review by kjgumbs — APPROVED** [review]

**Comment by tstrat** [comment]
Testing Pull Request Prior to solution to revert main - Please ignore

**Pull request closed without merging**
